### ISSUE TITLE
Override toxyproxy host uri

### ISSUE THREAD

**Issue by GeorgeTaveras1231** [Shopify/toxiproxy-ruby#17]
Would there be any negative side-effect to allowing the host uri to be changed from the default: 127.0.0.1:8474? 

Referencing [this](https://github.com/Shopify/toxiproxy-ruby/blob/master/lib/toxiproxy.rb#L10)

I'm working with a multi-container docker environment where it would be ideal to keep the toxyproxy server in a separate container from my source code. I would like to configure the Toxyproxy client to send requests to the separate container, rather than the home IP.

I'm also volunteering myself to making the change if you guys approve.

Thanks

**Comment by Sirupsen** [comment]
Entirely reasonable. Submit away!

**Comment by xthexder** [comment]
This seems like a reasonable configuration option to have.
cc @jpittis This is an option we should have the cli as well (https://github.com/Shopify/toxiproxy/pull/93)

:+1: if you want to add a `set_host()` call or similar.

**Comment by Sirupsen** [comment]
API should be something like:

```ruby
Toxiproxy.host = "http://127.0.0.1:8474"
```

It should automatically set it to a URI (if it's not already passed as one).

**Comment by GeorgeTaveras1231** [comment]
Great! Thanks for the feedback, I will work on this soon.

**Comment by GeorgeTaveras1231** [comment]
Are there any specific steps I should take as part of setting up the testing environment? Just saying because `rake test` fails by default.

**Comment by GeorgeTaveras1231** [comment]
NVM, just need to start up toxiproxy. Can I add this to the documentation?

**Comment by xthexder** [comment]
If you'd like you could add something about it to the readme, though there currently isn't a section for it. :pencil2: away

**Comment by thegedge** [comment]
We actually needed this functionality today, and have a branch with these changes ready to go (see https://github.com/Shopify/toxiproxy-ruby/compare/allow-setting-host). Did you have something put together @GeorgeTaveras1231, or would these changes be satisfactory? I can create the PR if so.

**Comment by GeorgeTaveras1231** [comment]
@thegedge your work looks good to me. I didn't actually get to work on anything due to an hour commute from work.
