### ISSUE TITLE
Action required: CircleCI v1.0 is EOL, this repo is impacted

### ISSUE THREAD

**Issue by ayatsynych** [Shopify/toxiproxy-ruby#30]
## This repository relies on CircleCI v1.0 which will be shut down on **Aug 31st**.

cc @fw42

**Comment by dentarg** [comment]
I think this can be closed, solved by https://github.com/Shopify/toxiproxy-ruby/pull/31

**Comment by chen-anders** [comment]
Closing this as we're on Github actions now.
